/*
 * Programmer:Victoria P., Arun V., and Kiera W.
 * Date: 8/8/2019
 * Program Name: FinaProject.java
 * Program Description: Creates the intro screen for the program.
 */
package finalproject;

/**
 *
 * @author vp
 */
public class FinaProject extends javax.swing.JFrame {
    //decliare object oPlayScreen of class PlayScreen
    PlayScreen oPlayScreen;
    /**
     * Creates new form FinaProject
     */
    public FinaProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTheUltimateHangman = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblCreatedBy = new javax.swing.JLabel();
        lblClickPlayToStart = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInstruction = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTheUltimateHangman.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        lblTheUltimateHangman.setForeground(new java.awt.Color(204, 0, 204));
        lblTheUltimateHangman.setText("The Ultimate Hangman");
        lblTheUltimateHangman.setFocusTraversalPolicyProvider(true);

        lblWelcome.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 255));
        lblWelcome.setText("Welcom to The Ultimate Hangman game!");

        lblCreatedBy.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblCreatedBy.setForeground(new java.awt.Color(0, 0, 255));
        lblCreatedBy.setText("Created By: Victoria P., Arun V., and Kiera w.");

        lblClickPlayToStart.setFont(new java.awt.Font("Niagara Solid", 1, 48)); // NOI18N
        lblClickPlayToStart.setForeground(new java.awt.Color(204, 0, 51));
        lblClickPlayToStart.setText("CLICK PLAY TO START!");

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lblInstructions.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblInstructions.setForeground(new java.awt.Color(0, 102, 102));
        lblInstructions.setText("Instructions:");

        txtInstruction.setColumns(20);
        txtInstruction.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        txtInstruction.setRows(5);
        txtInstruction.setText("\n 1. You are trying to guess a word.\n\n 2. Choose a letter you think is in the word.\n\n 3. If the letter exists in the word, it will appear in its proper position.\n\n 4. If it does not, a body part will appear.\n\n 5. You win when you have guessed the entire word.\n\n 6. You loose when you have hanged the man.");
        jScrollPane1.setViewportView(txtInstruction);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lblTheUltimateHangman, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lblCreatedBy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(lblClickPlayToStart))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(454, 454, 454)
                            .addComponent(btnPlay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInstructions)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTheUltimateHangman)
                .addGap(28, 28, 28)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreatedBy)
                .addGap(30, 30, 30)
                .addComponent(lblInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblClickPlayToStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnExit))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        //code for when the exit button is pressed
        System.exit(0);
    }                                       

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        //code for play button is pressed
        //set current form invisible
        this.setVisible(false);
        //create play screen
        //set so it is visible
        oPlayScreen = new PlayScreen();        
        oPlayScreen.setVisible(true);        
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinaProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClickPlayToStart;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTheUltimateHangman;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextArea txtInstruction;
    // End of variables declaration                   
}